version: 2 
project_name: cec-controller

builds:
  - main: .
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: -s -w
    binary: cec-controller

nfpms:
  - id: deb
    description: "CEC Controller Service"
    maintainer: "eliottness"
    homepage: "https://github.com/eliottness/cec-controller"
    license: "GLPv3"
    formats: [deb]
    vendor: "eliottness"
    section: "utils"
    priority: "optional"
    bindir: "/usr/bin"
  - id: rpm
    description: "CEC Controller Service"
    maintainer: "eliottness"
    homepage: "https://github.com/eliottness/cec-controller"
    license: "GLPv3"
    formats: [rpm]
    vendor: "eliottness"
    bindir: "/usr/bin"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
