name: Build CLI Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    - name: Build Linux amd64 Binary
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/cec-controller-amd64 main.go
    - name: Build Linux arm64 Binary
      run: |
        GOOS=linux GOARCH=arm64 go build -o dist/cec-controller-arm64 main.go
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cec-controller-linux
        path: dist/
