name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install libcec for testing
        run: |
          sudo apt-get update
          sudo apt-get install -y libcec-dev libp8-platform-dev

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcec-dev libp8-platform-dev gcc-aarch64-linux-gnu
          # Add arm64 architecture and install cross-compilation libraries
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y libcec-dev:arm64 libp8-platform-dev:arm64

      - name: Build Ubuntu amd64
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p dist/ubuntu-amd64
          go build -ldflags="-s -w" -o dist/ubuntu-amd64/cec-controller .

      - name: Build Ubuntu arm64
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc
          PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig
        run: |
          mkdir -p dist/ubuntu-arm64
          go build -ldflags="-s -w" -o dist/ubuntu-arm64/cec-controller .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cec-controller-binaries
          path: dist/
